/* Generated by JTB 1.4.4 */
package arbolxml;

import visitorxml.*;

public class lista_db implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeToken f2;

  public NodeToken f3;

  public NodeToken f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public lista_db(final NodeToken n0, final NodeToken n1, final NodeToken n2, final NodeToken n3, final NodeToken n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public lista_db(final NodeToken n0) {
    f0 = new NodeToken("<nombre>");
    f1 = n0;
    f2 = new NodeToken("</nombre>");
    f3 = new NodeToken("<path>");
    f4 = new NodeToken("\"");
    f5 = new NodeToken("</path>");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
