/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Analizador_usql.ParseException_usql;
import Ejecucion_usql.Instruccion_principal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mike
 */
public class Uiservidor extends javax.swing.JFrame {

    /**
     * Creates new form Uiservidor
     */
    public Uiservidor() throws IOException {
        initComponents();        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consolaServidor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        comandos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consolaServidor.setColumns(20);
        consolaServidor.setRows(5);
        jScrollPane1.setViewportView(consolaServidor);

        comandos.setColumns(20);
        comandos.setRows(5);
        comandos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comandosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(comandos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comandosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comandosKeyPressed
        try {
            if(evt.getKeyCode()==10){
                Instruccion_principal.instruccionPrincipal(comandos.getText());
                Debuger.imprimir();
            }
        } catch (IOException ex) {
            Logger.getLogger(Uiservidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException_usql ex) {
            Debuger.Debug(ex.getMessage(), false, null);
            Debuger.imprimir();
        }
    }//GEN-LAST:event_comandosKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comandos;
    public static javax.swing.JTextArea consolaServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
