/* Generated by JTB 1.4.4 */
package arbolply;

import visitorply.*;

public class Inicio implements INode {

  public NodeToken f0;

  public valor f1;

  public NodeListOptional f2;

  public NodeToken f3;

  public NodeOptional f4;

  private static final long serialVersionUID = 144L;

  public Inicio(final NodeToken n0, final valor n1, final NodeListOptional n2, final NodeToken n3, final NodeOptional n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public Inicio(final valor n0, final NodeListOptional n1, final NodeOptional n2) {
    f0 = new NodeToken("[");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("]");
    f4 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
