/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class alterar_tabla implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public NodeChoice f2;

  private static final long serialVersionUID = 144L;

  public alterar_tabla(final NodeToken n0, final NodeToken n1, final NodeChoice n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public alterar_tabla(final NodeToken n0, final NodeChoice n1) {
    f0 = new NodeToken("tabla");
    f1 = n0;
    f2 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
