/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class borrar implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public NodeToken f2;

  public NodeToken f3;

  public NodeOptional f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public borrar(final NodeToken n0, final NodeToken n1, final NodeToken n2, final NodeToken n3, final NodeOptional n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public borrar(final NodeToken n0, final NodeOptional n1) {
    f0 = new NodeToken("borrar");
    f1 = new NodeToken("en");
    f2 = new NodeToken("tabla");
    f3 = n0;
    f4 = n1;
    f5 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
