/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class caso implements INode_usql {

  public NodeToken f0;

  public exp_logica f1;

  public NodeToken f2;

  public NodeListOptional f3;

  private static final long serialVersionUID = 144L;

  public caso(final NodeToken n0, final exp_logica n1, final NodeToken n2, final NodeListOptional n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public caso(final exp_logica n0, final NodeListOptional n1) {
    f0 = new NodeToken("caso");
    f1 = n0;
    f2 = new NodeToken(":");
    f3 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
