/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class crear_funcion implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public NodeToken f2;

  public NodeOptional f3;

  public NodeToken f4;

  public tipo f5;

  public NodeToken f6;

  public NodeListOptional f7;

  public NodeToken f8;

  private static final long serialVersionUID = 144L;

  public crear_funcion(final NodeToken n0, final NodeToken n1, final NodeToken n2, final NodeOptional n3, final NodeToken n4, final tipo n5, final NodeToken n6, final NodeListOptional n7, final NodeToken n8) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
  }

  public crear_funcion(final NodeToken n0, final NodeOptional n1, final tipo n2, final NodeListOptional n3) {
    f0 = new NodeToken("funcion");
    f1 = n0;
    f2 = new NodeToken("(");
    f3 = n1;
    f4 = new NodeToken(")");
    f5 = n2;
    f6 = new NodeToken("{");
    f7 = n3;
    f8 = new NodeToken("}");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
