/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class crear_objeto implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public NodeToken f2;

  public lista_componentes f3;

  public NodeListOptional f4;

  public NodeToken f5;

  public NodeToken f6;

  private static final long serialVersionUID = 144L;

  public crear_objeto(final NodeToken n0, final NodeToken n1, final NodeToken n2, final lista_componentes n3, final NodeListOptional n4, final NodeToken n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public crear_objeto(final NodeToken n0, final lista_componentes n1, final NodeListOptional n2) {
    f0 = new NodeToken("objeto");
    f1 = n0;
    f2 = new NodeToken("(");
    f3 = n1;
    f4 = n2;
    f5 = new NodeToken(")");
    f6 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
