/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class Declarar implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public NodeListOptional f2;

  public NodeChoice f3;

  public NodeToken f4;

  private static final long serialVersionUID = 144L;

  public Declarar(final NodeToken n0, final NodeToken n1, final NodeListOptional n2, final NodeChoice n3, final NodeToken n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public Declarar(final NodeToken n0, final NodeListOptional n1, final NodeChoice n2) {
    f0 = new NodeToken("declarar");
    f1 = n0;
    f2 = n1;
    f3 = n2;
    f4 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
