/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.IRetArguVisitor;
import visitor.IRetVisitor;
import visitor.IVoidArguVisitor;
import visitor.IVoidVisitor;
import java.util.*;

public class NodeList implements INodeList {

  public ArrayList<INode_usql> nodes;

  private static final int allocTb[] = {1, 2, 3, 4, 5, 10, 20, 50};

  private int allocNb = 0;

  private static final long serialVersionUID = 144L;

  public NodeList() {
    nodes = new ArrayList<INode_usql>(allocTb[allocNb]);
  }

  public NodeList(final int sz) {
    nodes = new ArrayList<INode_usql>(sz);
  }

  public NodeList(final INode_usql firstNode) {
    nodes = new ArrayList<INode_usql>(allocTb[allocNb]);
    addNode(firstNode);
  }

  public NodeList(final int sz, final INode_usql firstNode) {
    nodes = new ArrayList<INode_usql>(sz);
    addNode(firstNode);
  }

  public void addNode(final INode_usql n) {
    if (++allocNb < allocTb.length)
      nodes.ensureCapacity(allocTb[allocNb]);
    else
      nodes.ensureCapacity((allocNb - allocTb.length + 2) * allocTb[(allocTb.length - 1)]);
    nodes.add(n);
  }

  public INode_usql elementAt(final int i) {
    return nodes.get(i); }

  public Iterator<INode_usql> elements() {
    return nodes.iterator(); }

  public int size() {
    return nodes.size(); }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
