/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.IRetArguVisitor;
import visitor.IRetVisitor;
import visitor.IVoidArguVisitor;
import visitor.IVoidVisitor;

import java.util.*;

public class NodeSequence implements INodeList {

  public ArrayList<INode_usql> nodes;

  private static final long serialVersionUID = 144L;

  public NodeSequence() {
    nodes = new ArrayList<INode_usql>();
  }

  public NodeSequence(final int sz) {
    nodes = new ArrayList<INode_usql>(sz);
  }

  public NodeSequence(final INode_usql firstNode) {
    nodes = new ArrayList<INode_usql>();
    addNode(firstNode);
  }

  public NodeSequence(final int sz, final INode_usql firstNode) {
    nodes = new ArrayList<INode_usql>(sz);
    addNode(firstNode);
  }

  public void addNode(final INode_usql n) {
    nodes.add(n);
  }

  public INode_usql elementAt(final int i) {
    return nodes.get(i); }

  public Iterator<INode_usql> elements() {
    return nodes.iterator(); }

  public int size() {
    return nodes.size(); }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
