/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class Para implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public Declarar f2;

  public exp_logica f3;

  public NodeToken f4;

  public NodeChoice f5;

  public NodeToken f6;

  public NodeToken f7;

  public NodeListOptional f8;

  public NodeToken f9;

  private static final long serialVersionUID = 144L;

  public Para(final NodeToken n0, final NodeToken n1, final Declarar n2, final exp_logica n3, final NodeToken n4, final NodeChoice n5, final NodeToken n6, final NodeToken n7, final NodeListOptional n8, final NodeToken n9) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
  }

  public Para(final Declarar n0, final exp_logica n1, final NodeChoice n2, final NodeListOptional n3) {
    f0 = new NodeToken("para");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = n1;
    f4 = new NodeToken(";");
    f5 = n2;
    f6 = new NodeToken(")");
    f7 = new NodeToken("{");
    f8 = n3;
    f9 = new NodeToken("}");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
