/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class seleccionar implements INode_usql {

  public NodeToken f0;

  public NodeChoice f1;

  public NodeListOptional f2;

  public NodeToken f3;

  public NodeToken f4;

  public NodeListOptional f5;

  public NodeOptional f6;

  public NodeOptional f7;

  private static final long serialVersionUID = 144L;

  public seleccionar(final NodeToken n0, final NodeChoice n1, final NodeListOptional n2, final NodeToken n3, final NodeToken n4, final NodeListOptional n5, final NodeOptional n6, final NodeOptional n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public seleccionar(final NodeChoice n0, final NodeListOptional n1, final NodeToken n2, final NodeListOptional n3, final NodeOptional n4, final NodeOptional n5) {
    f0 = new NodeToken("seleccionar");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("de");
    f4 = n2;
    f5 = n3;
    f6 = n4;
    f7 = n5;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
