/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class Si implements INode_usql {

  public NodeToken f0;

  public NodeToken f1;

  public exp_logica f2;

  public NodeToken f3;

  public NodeToken f4;

  public NodeListOptional f5;

  public NodeToken f6;

  public NodeOptional f7;

  private static final long serialVersionUID = 144L;

  public Si(final NodeToken n0, final NodeToken n1, final exp_logica n2, final NodeToken n3, final NodeToken n4, final NodeListOptional n5, final NodeToken n6, final NodeOptional n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public Si(final exp_logica n0, final NodeListOptional n1, final NodeOptional n2) {
    f0 = new NodeToken("si");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = new NodeToken(")");
    f4 = new NodeToken("{");
    f5 = n1;
    f6 = new NodeToken("}");
    f7 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
