/* Generated by JTB 1.4.4 */
package visitorply;

import Entorno.Entero;
import Entorno.Objeto;
import Entorno.Simbolo;
import Entorno.Texto;
import arbolply.*;
import java.util.*;
import proyecto.Contexto;

public class DepthFirstRetVisitor<R> implements IRetVisitor<R> {


  public R visit(final NodeChoice n) {
    final R nRes = n.choice.accept(this);
    return nRes;
  }

  public R visit(final NodeList n) {
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      final R sRes = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeListOptional n) {
    if (n.present()) {
      R nRes = null;
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        @SuppressWarnings("unused")
        R sRes = e.next().accept(this);
        }
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeOptional n) {
    if (n.present()) {
      final R nRes = n.node.accept(this);
      return nRes;
    } else
    return null;
  }

  public R visit(final NodeSequence n) {
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      R subRet = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeToken n) {
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final Inicio n) {
    Simbolo resultado = null;
    Objeto obj =  new Objeto("");
    n.f1.accept(this);
    Simbolo primero = (Simbolo) n.f1.accept(this);
    obj.valor.insertar(primero.nombre, primero);
    if(n.f2.present()){
        for(INode node : n.f2.nodes){
            NodeSequence ns =  (NodeSequence) node;
            Simbolo otro =(Simbolo) ns.nodes.get(1).accept(this);
            obj.valor.insertar(otro.nombre, otro);
        }
    }
    n.f2.accept(this);
    resultado =  new Simbolo("Raiz", obj.Tipo, obj);
    return (R)resultado;
  }

  public R visit(final valor n) {
    Simbolo s = null;    
    String nombre = n.f0.tokenImage.replace("\"", "");
    switch(n.f2.which){
        case 0:
            NodeToken tok =  (NodeToken) n.f2.choice;
            s =  new Simbolo(nombre, Contexto.TEX, new Texto(tok.tokenImage,Contexto.TEX));
            break;
        case 1:            
            NodeToken tok1 =  (NodeToken) n.f2.choice;
            s =  new Simbolo(nombre, Contexto.ENT, new Entero(tok1.tokenImage,Contexto.ENT));
            break;            
        case 2:            
            NodeToken tok2 =  (NodeToken) n.f2.choice;
            s =  new Simbolo(nombre, Contexto.TEX, new Texto(tok2.tokenImage,Contexto.TEX));
            break;
        case 3:
            Simbolo valor = (Simbolo) n.f2.choice.accept(this);
            s =  new Simbolo(nombre, Contexto.OBJ, valor.v);
            break;
    }
    return (R)s;
  }

  public R visit(final operador n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

}
