/* Generated by JTB 1.4.4 */
package visitorply;

import arbolply.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Inicio n, final A argu);

  public R visit(final valor n, final A argu);

  public R visit(final operador n, final A argu);

}
