/* Generated by JTB 1.4.4 */
package visitorply;

import arbolply.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Inicio n);

  public R visit(final valor n);

  public R visit(final operador n);

}
