/* Generated by JTB 1.4.4 */
package visitorply;

import arbolply.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);


  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Inicio n, final A argu);

  public void visit(final valor n, final A argu);

  public void visit(final operador n, final A argu);

}
