/* Generated by JTB 1.4.4 */
package visitorply;

import arbolply.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final Inicio n);

  public void visit(final valor n);

  public void visit(final operador n);

}
