/* Generated By:JavaCC: Do not edit this line. XmlParserConstants.java */
package Analizador_xml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int VERDADERO = 8;
  /** RegularExpression Id. */
  int FALSO = 9;
  /** RegularExpression Id. */
  int S_NUMBERO = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DATE = 13;
  /** RegularExpression Id. */
  int HORA = 14;
  /** RegularExpression Id. */
  int DIGITO = 15;
  /** RegularExpression Id. */
  int K_prueba = 16;
  /** RegularExpression Id. */
  int K_db = 17;
  /** RegularExpression Id. */
  int K_dbf = 18;
  /** RegularExpression Id. */
  int K_nombre = 19;
  /** RegularExpression Id. */
  int K_nombref = 20;
  /** RegularExpression Id. */
  int K_path = 21;
  /** RegularExpression Id. */
  int K_pathf = 22;
  /** RegularExpression Id. */
  int K_seek = 23;
  /** RegularExpression Id. */
  int K_seekf = 24;
  /** RegularExpression Id. */
  int K_tabla = 25;
  /** RegularExpression Id. */
  int K_tablaf = 26;
  /** RegularExpression Id. */
  int K_permiso = 27;
  /** RegularExpression Id. */
  int K_permisof = 28;
  /** RegularExpression Id. */
  int K_rows = 29;
  /** RegularExpression Id. */
  int K_rowsf = 30;
  /** RegularExpression Id. */
  int K_int = 31;
  /** RegularExpression Id. */
  int K_intf = 32;
  /** RegularExpression Id. */
  int K_doble = 33;
  /** RegularExpression Id. */
  int K_doblef = 34;
  /** RegularExpression Id. */
  int K_texto = 35;
  /** RegularExpression Id. */
  int K_textof = 36;
  /** RegularExpression Id. */
  int K_bool = 37;
  /** RegularExpression Id. */
  int K_boolf = 38;
  /** RegularExpression Id. */
  int K_date = 39;
  /** RegularExpression Id. */
  int K_datef = 40;
  /** RegularExpression Id. */
  int K_datehora = 41;
  /** RegularExpression Id. */
  int K_datehoraf = 42;
  /** RegularExpression Id. */
  int K_nulo = 43;
  /** RegularExpression Id. */
  int K_nulof = 44;
  /** RegularExpression Id. */
  int K_auto = 45;
  /** RegularExpression Id. */
  int K_autof = 46;
  /** RegularExpression Id. */
  int K_prim = 47;
  /** RegularExpression Id. */
  int K_primf = 48;
  /** RegularExpression Id. */
  int K_for = 49;
  /** RegularExpression Id. */
  int K_forf = 50;
  /** RegularExpression Id. */
  int K_unico = 51;
  /** RegularExpression Id. */
  int K_unicof = 52;
  /** RegularExpression Id. */
  int K_procedure = 53;
  /** RegularExpression Id. */
  int K_proceduref = 54;
  /** RegularExpression Id. */
  int K_object = 55;
  /** RegularExpression Id. */
  int K_objectf = 56;
  /** RegularExpression Id. */
  int K_obj = 57;
  /** RegularExpression Id. */
  int K_objf = 58;
  /** RegularExpression Id. */
  int K_atr = 59;
  /** RegularExpression Id. */
  int K_atrf = 60;
  /** RegularExpression Id. */
  int K_proc = 61;
  /** RegularExpression Id. */
  int K_procf = 62;
  /** RegularExpression Id. */
  int K_src = 63;
  /** RegularExpression Id. */
  int K_srcf = 64;
  /** RegularExpression Id. */
  int K_clave = 65;
  /** RegularExpression Id. */
  int K_clavef = 66;
  /** RegularExpression Id. */
  int K_usuario = 67;
  /** RegularExpression Id. */
  int K_usuariof = 68;
  /** RegularExpression Id. */
  int K_iden = 69;
  /** RegularExpression Id. */
  int K_idenf = 70;
  /** RegularExpression Id. */
  int S_IDENTIFICADOR = 71;
  /** RegularExpression Id. */
  int LETRA = 72;
  /** RegularExpression Id. */
  int ESPECIAL = 73;
  /** RegularExpression Id. */
  int CADENA_LITERAL = 74;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"1\"",
    "\"0\"",
    "<S_NUMBERO>",
    "<FLOAT>",
    "<INTEGER>",
    "<DATE>",
    "<HORA>",
    "<DIGITO>",
    "\"prueba\"",
    "\"<db>\"",
    "\"</db>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<seek>\"",
    "\"</seek>\"",
    "\"<tabla>\"",
    "\"</tabla>\"",
    "\"<permiso>\"",
    "\"</permiso>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<int>\"",
    "\"</int>\"",
    "\"<doble>\"",
    "\"</doble>\"",
    "\"<texto>\"",
    "\"</texto>\"",
    "\"<bool>\"",
    "\"</bool>\"",
    "\"<date>\"",
    "\"</date>\"",
    "\"<datehora>\"",
    "\"</datehora>\"",
    "\"<nulo>\"",
    "\"</nulo>\"",
    "\"<auto>\"",
    "\"</auto>\"",
    "\"<prim>\"",
    "\"</prim>\"",
    "\"<for>\"",
    "\"</for>\"",
    "\"<unico>\"",
    "\"</unico>\"",
    "\"<procedure>\"",
    "\"</procedure>\"",
    "\"<object>\"",
    "\"</object>\"",
    "\"<obj>\"",
    "\"</obj>\"",
    "\"<atr>\"",
    "\"</atr>\"",
    "\"<proc>\"",
    "\"</proc>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<clave>\"",
    "\"</clave>\"",
    "\"<usuario>\"",
    "\"</usuario>\"",
    "<K_iden>",
    "<K_idenf>",
    "<S_IDENTIFICADOR>",
    "<LETRA>",
    "<ESPECIAL>",
    "<CADENA_LITERAL>",
  };

}
