/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;
import java.util.*;
import Analizador_xml.*;
import Analizador_usql.*;
import proyecto.*;
import Entorno.*;
import Ejecucion_usql.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdk.internal.org.objectweb.asm.tree.TryCatchBlockNode;

public class DepthFirstRetVisitor_usql<R> implements IRetVisitor<R> {

    public INode_usql BackUpDump;
    public Ent levantado = new Ent(null);
    private boolean flujo =  false;
    private Ent global =  new Ent(null);
    
    
    public R visit(final NodeChoice n) {
        final R nRes = n.choice.accept(this);
        return nRes;
    }

    public R visit(final NodeList n) {
        R nRes = null;
        for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {                        
            try{
                INode_usql no =  (INode_usql)e.next();
                final R sRes = no.accept(this);
                if(Contexto.Backup){
                    DepthFirstVoidVisitor vi =  new DepthFirstVoidVisitor();
                    no.accept(vi);
                    Contexto.contenidoBitacora = vi.instrucciones.toString() + "\n";
                    //Contexto.EscribirBdDump(Contexto.contenidoBitacora);
                }
            }catch(NullPointerException ex){
                Debuger.Debug(ex);
            }
        }        
        return nRes;
    }

    public R visit(final NodeListOptional n) {
        if (n.present()) {
            R nRes = null;
            for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
                @SuppressWarnings("unused")
                R sRes = e.next().accept(this);
            }
            return nRes;
        } else {
            return null;
        }
    }

    public R visit(final NodeOptional n) {
        if (n.present()) {
            final R nRes = n.node.accept(this);
            return nRes;
        } else {
            return null;
        }
    }

    public R visit(final NodeSequence n) {
        R nRes = null;
        for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
            @SuppressWarnings("unused")
            R subRet = e.next().accept(this);
        }
        return nRes;
    }

    public R visit(final NodeToken n) {
        R nRes = null;
        @SuppressWarnings("unused")
        final String tkIm = n.tokenImage;
        return nRes;
    }

    public R visit(final Inicio n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final listasentencias n) {
        Simbolo retorno =  new Simbolo("temp", "", new Texto("", ""));
        switch (n.f0.which) {
            case 0:
                //crear base de datos
                NodeSequence dd = (NodeSequence) n.f0.choice;
                NodeChoice choice = (NodeChoice) dd.nodes.get(1);
                switch (choice.which) {
                    case 0:
                        Instruccion_crear.CrearBase((crear_base) choice.choice);
                        break;
                    case 1:
                        Instruccion_crear.CrearTabla((crear_tabla) choice.choice);
                        break;
                    case 2:
                        Instruccion_crear.CrearObjeto((crear_objeto) choice.choice);
                        break;
                    case 3:
                        Instruccion_crear.CrearFunProc((crear_procedimiento) choice.choice);
                        break;
                    case 4:
                        Instruccion_crear.CrearFunProc((crear_funcion) choice.choice);
                        break;
                    case 5:
                        Instruccion_crear.CrearUsuario((crear_usuario) choice.choice);
                        break;
                }
                break;
            case 1:
                NodeSequence Usar = (NodeSequence) n.f0.choice;
                NodeToken Tusar = (NodeToken) Usar.nodes.get(1);
                String NombreBase = Tusar.tokenImage;
                Instruccion_usar.UsarBase(NombreBase);
                Contexto.Backup =  true;
                break;
            case 2:
                NodeSequence dd_alterar = (NodeSequence) n.f0.choice;
                NodeChoice choice_alterar = (NodeChoice) dd_alterar.nodes.get(1);
                switch (choice_alterar.which) {
                    case 0:
                        choice_alterar.choice.accept(this);
                        break;
                    case 1:
                        choice_alterar.choice.accept(this);
                        break;
                    case 2:
                        Instruccion_alterar.AlterarUsuario((Simbolo) choice_alterar.choice.accept(this));
                        break;
                    case 3:
                        break;
                }
                break;
            case 3:
                NodeSequence ddd_alterar = (NodeSequence) n.f0.choice;
                NodeChoice choice_eliminar = (NodeChoice) ddd_alterar.nodes.get(1);
                Simbolo choiceSimbolo = (Simbolo) choice_eliminar.choice.accept(this);
                switch (choice_eliminar.which) {
                    case 0:
                        Instruccion_eliminar.EliminarUsuario(choiceSimbolo);
                        break;
                    case 1:
                        Instruccion_eliminar.EliminarTabla(choiceSimbolo);
                        break;
                    case 2:
                        Instruccion_eliminar.EliminarBd(choiceSimbolo);
                        break;
                    case 3:
                        Instruccion_eliminar.EliminarObjeto(choiceSimbolo);
                        break;
                }
                break;
            case 4:
                //insertar
                Instruccion_insetar.InsertarRegistro((insertar)n.f0.choice, this);
                break;
            case 5:
                break;
            case 6:
                break;
            case 7:
                break;
            case 8:
                //otorgar 
                INode_usql dd_otorgar = (INode_usql) n.f0.choice;
                Instruccion_otorgar.OtorgarPermisos((Simbolo) dd_otorgar.accept(this));
                break;
            case 9:
                INode_usql dd_denegar = (INode_usql) n.f0.choice;
                Instruccion_denegar.DenegarPermisos((Simbolo) dd_denegar.accept(this));
                break;
            case 10:
                INode_usql dd_declarar = (INode_usql) n.f0.choice;
                return (R) dd_declarar.accept(this);                   
            case 11:
                INode_usql dd_asignacion = (INode_usql) n.f0.choice;
                return (R) dd_asignacion.accept(this);  
            case 12:
                INode_usql dd_si = (INode_usql) n.f0.choice;
                return (R) dd_si.accept(this);                
            case 13:
                INode_usql dd_selecciona = (INode_usql) n.f0.choice;
                return (R) dd_selecciona.accept(this);                 
            case 14:
                INode_usql dd_para = (INode_usql) n.f0.choice;
                return (R) dd_para.accept(this);                                 
            case 15:
                INode_usql dd_mientras = (INode_usql) n.f0.choice;
                return (R) dd_mientras.accept(this);
            case 16:
                INode_usql dd_imprimir = (INode_usql) n.f0.choice;
                return dd_imprimir.accept(this);
            case 17:
                break;
            case 18:
                // back up
                break;
            case 19:
                //restarura up
                break;
            case 20:
                NodeSequence dd_expresion = (NodeSequence) n.f0.choice;
                Debuger.Debug(null, false, (Simbolo) dd_expresion.nodes.get(0).accept(this));
                break;
        }
        return (R)retorno;
    }

    public R visit(final eliminar_usuario n) {
        String identificadorUsuario = n.f1.tokenImage;
        Simbolo user = new Simbolo(identificadorUsuario, identificadorUsuario, null);
        return (R) user;
    }

    public R visit(final eliminar_tabla n) {
        String identificadorTabla = n.f1.tokenImage;
        Simbolo s = new Simbolo(identificadorTabla, "", null);
        return (R) s;
    }

    public R visit(final eliminar_base n) {
        String identificador = n.f1.tokenImage;
        Simbolo s = new Simbolo(identificador, "", null);
        return (R) s;
    }

    public R visit(final eliminar_objeto n) {
        String identificador = n.f1.tokenImage;
        Simbolo s = new Simbolo(identificador, identificador, null);
        return (R) s;
    }

    public R visit(final alterar_usuario n) {
        String nombreUsuario = n.f1.tokenImage;
        String claveUsuario = n.f5.tokenImage;
        Usuario_ent user = new Usuario_ent(nombreUsuario, claveUsuario);
        Simbolo sreturn = new Simbolo(nombreUsuario, "", user);
        return (R) sreturn;
    }

    public R visit(final alterar_tabla n) {
        n.f0.accept(this);
        String identificador = n.f1.tokenImage;//identificador
        NodeChoice no = n.f2;
        switch (no.which) {
            case 0:
                Instruccion_alterar.AgregarTabla((agregar_tabla) no.choice, identificador);
                break;
            case 1:
                Instruccion_alterar.QuitarTabla((quitar) no.choice, identificador);
                break;
        }
        return null;
    }

    public R visit(final alterar_objeto n) {
        n.f0.accept(this);
        String identificador = n.f1.tokenImage;//identificador
        NodeChoice no = n.f2;
        switch (no.which) {
            case 0:
                Instruccion_alterar.AgregarObjeto((agregar_objeto) no.choice, identificador);
                break;
            case 1:
                Instruccion_alterar.QuitarObjeto((quitar) no.choice, identificador);
                break;
        }
        return null;
    }

    public R visit(final agregar_tabla n) {
        R nRes = null;
        Tabla t = new Tabla("");
        NodeSequence ns = n.f2;
        Simbolo primerAtributo = (Simbolo) ns.nodes.get(0).accept(this);
        t.valores.add(primerAtributo);
        if (n.f3.present()) {
            for (int i = 0; i < n.f3.size(); i++) {
                NodeSequence ns1 = (NodeSequence) n.f3.nodes.get(i);
                Simbolo siguienteAtributo = (Simbolo) ns1.nodes.get(1).accept(this);
                t.valores.add(siguienteAtributo);
            }
        }
        Simbolo NuevosAtributos = new Simbolo("temp", "", t);
        return (R) NuevosAtributos;
    }

    public R visit(final quitar n) {
        Tabla t = new Tabla("");
        Simbolo primerAtributo = new Simbolo(n.f1.tokenImage, "", null);
        t.valores.add(primerAtributo);
        if (n.f2.present()) {
            for (INode_usql n1 : n.f2.nodes) {
                NodeSequence ns = (NodeSequence) n1;
                NodeToken tok = (NodeToken) ns.nodes.get(1);
                Simbolo siguienteAtributo = new Simbolo(tok.tokenImage, "", null);
                t.valores.add(siguienteAtributo);
            }
        }
        Simbolo tablaTemporal = new Simbolo("temporal", "", t);
        return (R) tablaTemporal;
    }

    public R visit(final agregar_objeto n) {
        Tabla val = new Tabla("");
        NodeSequence ns = n.f2;
        Simbolo primerComponente = (Simbolo) ns.nodes.get(0).accept(this);
        val.valores.add(primerComponente);
        if (n.f3.present()) {
            for (int i = 0; i < n.f3.size(); i++) {
                NodeSequence ns1 = (NodeSequence) n.f3.nodes.get(i);
                Simbolo siguienteComponente = (Simbolo) ns1.nodes.get(1).accept(this);
                val.valores.add(siguienteComponente);
            }
        }
        Simbolo temp = new Simbolo("temporal", "", val);
        return (R) temp;
    }

    public R visit(final crear_base n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final crear_tabla n) {
        R nRes = null;
        Simbolo s;
        Tabla t = new Tabla("");
        t.permisos = "";
        n.f2.accept(this);
        Simbolo patri = (Simbolo) n.f3.nodes.get(0).accept(this); //primer atributo nodesequence
        t.valores.add(patri);
        NodeListOptional nlo = n.f4; //lista de otros atrib
        if (nlo.present()) {
            for (int c = 0; c < nlo.size(); c++) {
                NodeSequence ns = (NodeSequence) nlo.nodes.get(c);
                Simbolo otrib = (Simbolo) ns.nodes.get(1).accept(this);
                if (Contexto.ExisteColumna(t.valores, otrib.nombre)) {
                    Debuger.Debug("La tabla " + n.f1.tokenImage + " ya tiene una columna con el nombre " + otrib.nombre);
                } else {
                    t.valores.add(otrib);
                }
            }
        }
        t.Tipo = n.f1.tokenImage;
        s = new Simbolo(n.f1.tokenImage, "", t);
        nRes = (R) s;
        return nRes;
    }

    public R visit(final lista_atributos n) {
        R nRes = null;
        Columna c = new Columna(null, "");
        Simbolo tipo = (Simbolo) n.f0.accept(this);
        Simbolo colum = new Simbolo(n.f1.tokenImage, tipo.tipo, null);
        if (n.f2.present()) {
            NodeList nl = (NodeList) n.f2.node;
            for (int i = 0; i < nl.size(); i++) {
                Simbolo complemento = (Simbolo) nl.nodes.get(i).accept(this);
                c.atributos.add(complemento);
            }
        }
        colum.v = c;
        nRes = (R) colum;
        return nRes;
    }

    public R visit(final tipo n) {
        R nRes = null;
        Simbolo s = null;
        switch (n.f0.which) {
            case 0:
                s = new Simbolo("", Contexto.TEX, null);
                break;
            case 1:
                s = new Simbolo("", Contexto.ENT, null);
                break;
            case 2:
                s = new Simbolo("", Contexto.DOB, null);
                break;
            case 3:
                s = new Simbolo("", Contexto.BOl, null);
                break;
            case 4:
                s = new Simbolo("", Contexto.DAT, null);
                break;
            case 5:
                s = new Simbolo("", Contexto.DATH, null);
                break;
            case 6:
                NodeToken nt = (NodeToken) n.f0.choice;
                s = new Simbolo("", nt.tokenImage, null);
                break;
        }
        nRes = (R) s;
        return nRes;
    }

    public R visit(final complemento_campo n) {
        R nRes = null;
        Simbolo s = null;
        switch (n.f0.which) {
            case 0:
                s = new Simbolo("nulo", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 1:
                s = new Simbolo("nulo", Contexto.BOl, new Bool("0", Contexto.BOl));
                break;
            case 2:
                s = new Simbolo("prim", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 3:
                NodeSequence ns = (NodeSequence) n.f0.choice;
                NodeToken tk = (NodeToken) ns.nodes.get(1);
                NodeToken tk1 = (NodeToken) ns.nodes.get(2);
                String referencia = tk.tokenImage;
                String colRef =  tk1.tokenImage;
                if (!levantado.existe(referencia)) {
                    Debuger.Debug("Error la tabla a la que se hace referencia no existe...", false, null);
                    Debuger.Debug("Objeto no encontrado... " + referencia, false, null);
                    return null;
                }else{
                    Simbolo ss =  levantado.Buscar(referencia);
                    Tabla t = (Tabla) ss.v;
                    if(!Contexto.ExisteColumna(t.valores, colRef)){
                        Debuger.Debug("Error la tabla no tiene ningun atributo con nombre" + colRef + "...", false, null);                        
                        return null;
                    }
                }
                s = new Simbolo("for", Contexto.BOl, new Bool(referencia+"_"+colRef, Contexto.BOl));
                break;
            case 4:
                s = new Simbolo("auto", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 5:
                s = new Simbolo("unico", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
        }
        nRes = (R) s;
        return nRes;
    }

    public R visit(final crear_objeto n) {
        Objeto obj = new Objeto("");
        n.f1.accept(this); //id
        Simbolo primero = (Simbolo) n.f3.accept(this); //primer atributo
        obj.valor.insertar(primero.nombre, primero);
        n.f4.accept(this);
        NodeListOptional nlo = n.f4; //lista de otros atrib
        if (nlo.present()) {
            for (int c = 0; c < nlo.size(); c++) {
                NodeSequence ns = (NodeSequence) nlo.nodes.get(c);
                Simbolo otrib = (Simbolo) ns.nodes.get(1).accept(this);
                obj.valor.insertar(otrib.nombre, otrib);
            }
        }
        obj.Tipo = n.f1.tokenImage;
        Simbolo nres = new Simbolo(n.f1.tokenImage, n.f1.tokenImage, obj);
        return (R) nres;
    }

    public R visit(final lista_componentes n) {
        Simbolo tipo = (Simbolo) n.f0.accept(this); //tipo
        Simbolo s = new Simbolo(n.f1.tokenImage, tipo.tipo, null);
        return (R) s;
    }

    public R visit(final crear_procedimiento n) {
        String identificador = n.f1.tokenImage; //identificador                                 
        DepthFirstVoidVisitor ContenidoInstrucciones = new DepthFirstVoidVisitor();
        n.f6.accept(ContenidoInstrucciones); //instrucciones       
        String instrucciones = ContenidoInstrucciones.instrucciones.toString();
        FuncionProc func = new FuncionProc(n.f6);
        if (n.f3.present()) {
            NodeSequence ns = (NodeSequence) n.f3.node;
            lista_parametros parametor = (lista_parametros) ns.nodes.get(0);
            func.parametros.add((Simbolo) parametor.accept(this));
            NodeListOptional nlo = (NodeListOptional) ns.nodes.get(1);
            for (int i = 0; i < nlo.size(); i++) {
                NodeSequence ns1 = (NodeSequence) nlo.nodes.get(i);
                Simbolo param = (Simbolo) ns1.nodes.get(1).accept(this);
                func.parametros.add(param);
            }
        }
        func.permisos = "\"\"";
        func.src = instrucciones;
        Simbolo nres = new Simbolo(identificador, "", func);
        return (R) nres;
    }

    public R visit(final lista_parametros n) {
        R nRes = null;
        Simbolo tipo = (Simbolo) n.f0.accept(this);
        String nombre = n.f1.tokenImage;
        Simbolo param = new Simbolo(nombre, tipo.tipo, null);
        return (R) param;
    }

    public R visit(final crear_funcion n) {
        String identificador = n.f1.tokenImage; //identificador                        
        Simbolo tipo_func = (Simbolo) n.f5.accept(this);
        DepthFirstVoidVisitor ContenidoInstrucciones = new DepthFirstVoidVisitor();
        n.f7.accept(ContenidoInstrucciones); //instrucciones       
        String instrucciones = ContenidoInstrucciones.instrucciones.toString();
        FuncionProc func = new FuncionProc(n.f7);
        if (n.f3.present()) {
            NodeSequence ns = (NodeSequence) n.f3.node;
            lista_parametros parametor = (lista_parametros) ns.nodes.get(0);
            func.parametros.add((Simbolo) parametor.accept(this));
            NodeListOptional nlo = (NodeListOptional) ns.nodes.get(1);
            for (int i = 0; i < nlo.size(); i++) {
                NodeSequence ns1 = (NodeSequence) nlo.nodes.get(i);
                Simbolo param = (Simbolo) ns1.nodes.get(1).accept(this);
                func.parametros.add(param);
            }
        }
        func.permisos = "\"\"";
        func.src = instrucciones;
        func.Tipo = tipo_func.tipo;
        Simbolo nres = new Simbolo(identificador, tipo_func.tipo, func);
        return (R) nres;
    }

    public R visit(final lista_sentencias_p n) {        
        return (R)n.f0.accept(this);        
    }

    public R visit(final Retorno n) {
                
        Simbolo retorno = (Simbolo)n.f1.accept(this); //retorno de funcion;        
        Simbolo ret =  new Simbolo("temp", "", new Texto(Contexto.RETORNO, Contexto.TEX));
        return (R)ret;
    }

    public R visit(final crear_usuario n) {
        Usuario_ent us = new Usuario_ent(n.f1.tokenImage, n.f5.tokenImage);
        Simbolo s = new Simbolo(us.nombre, "", us);
        return (R) s;
    }

    public R visit(final insertar n) {
        R nRes = null;                       
        return nRes;
    }

    public R visit(final lista_expresion n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final expresion n) {
        Simbolo izquierdo = (Simbolo) n.f0.accept(this);
        NodeListOptional op = n.f1;
        if (op.present()) {
            for (INode_usql node : op.nodes) {
                NodeChoice choice = (NodeChoice) node;
                NodeSequence ns = (NodeSequence) choice.choice;
                Simbolo derecho = (Simbolo) ns.nodes.get(1).accept(this);
                switch (choice.which) {
                    case 0:
                        izquierdo.v = Operaciones_aritmeticas.OperacionSuma(izquierdo, derecho);
                        break;
                    case 1:
                        izquierdo.v = Operaciones_aritmeticas.OperacionResta(izquierdo, derecho);
                        break;
                }
            }
        }
        return (R) izquierdo;
    }

    public R visit(final g n) {
        Simbolo izquierdo = (Simbolo) n.f0.accept(this);
        NodeListOptional op = n.f1;
        if (op.present()) {
            for (INode_usql node : op.nodes) {
                NodeSequence ns = (NodeSequence) node;
                Simbolo derecho = (Simbolo) ns.nodes.get(1).accept(this);
                izquierdo.v = Operaciones_aritmeticas.OperacionPotencia(izquierdo, derecho);
            }
        }
        return (R) izquierdo;
    }

    public R visit(final t n) {
        Simbolo izquierdo = (Simbolo) n.f0.accept(this);
        NodeListOptional op = n.f1;
        if (op.present()) {
            for (INode_usql node : op.nodes) {
                NodeChoice choice = (NodeChoice) node;
                NodeSequence ns = (NodeSequence) choice.choice;
                Simbolo derecho = (Simbolo) ns.nodes.get(1).accept(this);
                switch (choice.which) {
                    case 0:
                        izquierdo.v = Operaciones_aritmeticas.OperacionMultiplicacion(izquierdo, derecho);
                        break;
                    case 1:
                        izquierdo.v = Operaciones_aritmeticas.OperacionDivision(izquierdo, derecho);
                        break;
                }
            }
        }
        return (R) izquierdo;
    }

    public R visit(final f n) {
        Simbolo iz = new Simbolo("temp", "", null);
        NodeChoice nc = n.f0;
        switch (nc.which) {
            case 0:
                iz = (Simbolo) nc.choice.accept(this);
                break;
            case 1:
                NodeSequence ns = (NodeSequence) n.f0.choice;
                iz = (Simbolo) ns.nodes.get(1).accept(this);
                iz.v = Operaciones_aritmeticas.OperacionMinus(iz);
                break;
        }
        return (R) iz;
    }

    public R visit(final h n) {
        Simbolo iz = new Simbolo("temp", "", null);
        NodeChoice nc = n.f0;
        switch (nc.which) {
            case 0:
                NodeToken tok_doble = (NodeToken) nc.choice;
                iz.v = new Doble(tok_doble.tokenImage, "");
                break;
            case 1:
                NodeToken tok_entero = (NodeToken) nc.choice;
                iz.v = new Entero(tok_entero.tokenImage, "");
                break;
            case 2:
                NodeSequence ns_exp_log = (NodeSequence) nc.choice;
                iz = (Simbolo) ns_exp_log.nodes.get(1).accept(this);
                break;
            case 3:
                //identificadores por el momento me falta...
                NodeSequence ns = (NodeSequence)nc.choice;
                NodeToken token1 =  (NodeToken) ns.nodes.get(0); //el primer token 
                NodeOptional op1 =  (NodeOptional) ns.nodes.get(1);
                if(op1.present()){
                    NodeChoice choice =  (NodeChoice) op1.node;
                    switch(choice.which){
                        case 0:
                            NodeSequence ns1  =(NodeSequence) choice.choice;
                            NodeToken to = (NodeToken) ns1.nodes.get(1);
                            Simbolo padre =  this.global.Buscar(token1.tokenImage);
                            if(padre != null){
                                Objeto ob1 = (Objeto) padre.v;
                                Simbolo hijo =  ob1.valor.Buscar(to.tokenImage);
                                if(hijo != null){
                                    iz.v = hijo.v;
                                }else{
                                    Debuger.Debug("El objeto con nombre " + token1.tokenImage + " no tiene ningun atributo con nombre " + to.tokenImage + "...", false, null);
                                }
                            }else{
                                Debuger.Debug("El objeto con nombre " + token1.tokenImage + " no existe..." , false, null);
                            }
                            return (R)iz;
                        case 1:
                            //hacer la llamada del metodo
                            break;
                    }
                }
                Simbolo aux = global.Buscar(token1.tokenImage);
                iz.v = aux.v;
                break;
            case 4:
                NodeToken tok_cadena = (NodeToken) nc.choice;
                iz.v = new Texto(tok_cadena.tokenImage, "");
                break;
            case 5:
                //funcion fecha
                break;
            case 6:
                //funcion fechahora
                break;
            case 7:
                iz.v = new Bool("1", "");
                break;
            case 8:
                iz.v = new Bool("0", "");
                break;
            case 9:
                NodeSequence ns_date = (NodeSequence) nc.choice;
                NodeToken token = (NodeToken) ns_date.nodes.get(0);
                NodeOptional op = (NodeOptional) ns_date.nodes.get(1);
                iz.v = new Fecha_tipo(token.tokenImage, "");
                if (op.present()) {
                    NodeToken tok = (NodeToken) op.node;
                    iz.v = new Fecha_hora_tipo(token.tokenImage + tok.tokenImage, "");
                }
                break;
        }
        return (R) iz;
    }

    public R visit(final exp_relacional n) {        
        Simbolo iz = null;
        Simbolo der;
        switch (n.f0.which) {
            case 0:
                NodeSequence ns = (NodeSequence) n.f0.choice;
                iz = (Simbolo) ns.nodes.get(0).accept(this);
                NodeOptional nc = (NodeOptional) ns.nodes.get(1);
                if (nc.present()) {
                    NodeChoice ns1 = (NodeChoice) nc.node;
                    NodeSequence ns2 = (NodeSequence) ns1.choice;
                    switch (ns1.which) {
                        case 0:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionMenor(iz, der);
                            break;
                        case 1:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionMayor(iz, der);
                            break;
                        case 2:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionMenorIgual(iz, der);
                            break;
                        case 3:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionMayorIgual(iz, der);
                            break;
                        case 4:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionIgualdad(iz, der);
                            break;
                        case 5:
                            der = (Simbolo) ns2.nodes.get(1).accept(this);
                            iz.v = Operaciones_aritmeticas.OperacionDiferente(iz, der);
                            break;
                    }
                }

                break;
            case 1:
                NodeSequence ns1 = (NodeSequence) n.f0.choice;
                iz = (Simbolo) ns1.nodes.get(1).accept(this);
                iz.v = Operaciones_aritmeticas.OperacionNot(iz);
                break;
        }
        return (R) iz;
    }

    public R visit(final exp_logica n) {
        Simbolo izquierdo = (Simbolo) n.f0.accept(this);
        NodeListOptional op = n.f1;
        if (op.present()) {
            for (INode_usql node : op.nodes) {
                NodeSequence ns = (NodeSequence) node;
                Simbolo derecho = (Simbolo) ns.nodes.get(1).accept(this);
                izquierdo.v = Operaciones_aritmeticas.OperacionOr(izquierdo, derecho);
            }
        }
        return (R) izquierdo;
    }

    public R visit(final exp_or n) {
        Simbolo izquierdo = (Simbolo) n.f0.accept(this);
        NodeListOptional op = n.f1;
        if (op.present()) {
            for (INode_usql node : op.nodes) {
                NodeSequence ns = (NodeSequence) node;
                Simbolo derecho = (Simbolo) ns.nodes.get(1).accept(this);
                izquierdo.v = Operaciones_aritmeticas.OperacionAnd(izquierdo, derecho);
            }
        }
        return (R) izquierdo;
    }

    public R visit(final exp_and n) {
        return (R) n.f0.accept(this);
    }

    public R visit(final actualizar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        n.f8.accept(this);
        n.f9.accept(this);
        n.f10.accept(this);
        n.f11.accept(this);
        n.f12.accept(this);
        n.f13.accept(this);
        return nRes;
    }

    public R visit(final borrar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        return nRes;
    }

    public R visit(final seleccionar n) {                
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        return nRes;
    }

    public R visit(final otorgar n) {
        Tabla val = new Tabla("");
        String idUsuario = n.f2.tokenImage;
        String idBd = n.f4.tokenImage;
        NodeToken tok = (NodeToken) n.f6.choice;
        String queObjeto = tok.tokenImage;
        Simbolo bd = new Simbolo(idBd, "", null);
        Simbolo usuario = new Simbolo(idUsuario, idBd, null);
        Simbolo objeto = new Simbolo(queObjeto, queObjeto, null);
        val.valores.add(bd);
        val.valores.add(usuario);
        val.valores.add(objeto);
        Simbolo otorgar = new Simbolo("otorgar", "", val);
        return (R) otorgar;
    }

    public R visit(final denegar n) {
        Tabla val = new Tabla("");
        String idUsuario = n.f2.tokenImage;
        String idBd = n.f4.tokenImage;
        NodeToken tok = (NodeToken) n.f6.choice;
        String queObjeto = tok.tokenImage;
        Simbolo bd = new Simbolo(idBd, "", null);
        Simbolo usuario = new Simbolo(idUsuario, idBd, null);
        Simbolo objeto = new Simbolo(queObjeto, queObjeto, null);
        val.valores.add(bd);
        val.valores.add(usuario);
        val.valores.add(objeto);
        Simbolo otorgar = new Simbolo("otorgar", "", val);
        return (R) otorgar;
    }

    public R visit(final Declarar n) {
        Simbolo retorno =  new Simbolo("temp", "vacio", new Texto("", ""));
        Simbolo exp_l = null;
        Simbolo tipo = null;
        Simbolo tipo_objeto = null;
        Simbolo primerid =  new Simbolo(n.f1.tokenImage, "", null);
        Instruccion_declarar dec =  new Instruccion_declarar(this.global);
        NodeListOptional lista_ide = n.f2; //lista  id                      
        switch(n.f3.which){
            case 0:
                NodeSequence ns =  (NodeSequence) n.f3.choice;
                tipo =  (Simbolo) ns.nodes.get(0).accept(this);                
                NodeOptional op =  (NodeOptional)ns.nodes.get(1);
                NodeSequence ns1;
                if(op.present()){
                    ns1 = (NodeSequence) op.node;
                    exp_l =(Simbolo) ns1.nodes.get(1).accept(this);                    
                }
                break;
            case 1:
                NodeToken tok =  (NodeToken) n.f3.choice;
                tipo_objeto = new Simbolo ("temp", tok.tokenImage, null);
                break;
        }  
        if(tipo !=  null && Contexto.EsObjeto(tipo.tipo) == false){
            Instruccion_declarar Dec =  new Instruccion_declarar(this.global);
            Dec.declararVar(tipo, exp_l, primerid, lista_ide);
        }else{
            Instruccion_declarar dec1  = new Instruccion_declarar(this.global);
            dec1.declararObjeto(primerid.nombre, (tipo ==  null)?tipo_objeto.tipo:tipo.tipo);
        }        
        return (R)retorno;
    }

    public R visit(final asignacion n) {
        Simbolo retorno =  new Simbolo("temporal", "", new Texto("", ""));
        String idVar =  n.f0.tokenImage;
        Simbolo var =  this.global.Buscar(idVar);
        if(var != null){
            if(n.f1.present()){
                NodeSequence ns =  (NodeSequence) n.f1.node;
                NodeToken tok =  (NodeToken) ns.nodes.get(1);
                Instruccion_declarar asig14 =  new Instruccion_declarar(this.global);
                asig14.AsignarObjeto(var, tok.tokenImage, (Simbolo)n.f3.accept(this));
            }else{
                Instruccion_declarar asig =  new Instruccion_declarar(this.global);
                asig.AsignarVar(var, (Simbolo)n.f3.accept(this));
            }
        }else{
            Debuger.Debug("La variable con nombre " + idVar + " no ha sido declarada...", false, null);
        }        
        return (R)retorno;
    }

    public R visit(final Si n) {
        Simbolo exp_logica = (Simbolo) n.f2.accept(this); // expresion logica    
        Simbolo ret = new Simbolo("temporal", "", new Texto("vacio", Contexto.TEX));
        if (exp_logica.v.ABool()) {
            for (INode_usql node : n.f5.nodes) {
                ret = (Simbolo) node.accept(this);
                if (ret.v.ACadena().equals(Contexto.RETORNO)) {
                    return (R) ret;
                } else if (ret.v.ACadena().equals(Contexto.DETENER) && flujo) {
                    return (R) ret;
                }
            }
        } else {
            NodeOptional no = (NodeOptional) n.f7;
            if (no.present()) {
                NodeSequence ns = (NodeSequence) no.node;
                NodeListOptional nlto = (NodeListOptional) ns.nodes.get(2);
                if (nlto.present()) {
                    for (INode_usql node : nlto.nodes) {
                        ret = (Simbolo) node.accept(this);
                        if (ret.v.ACadena().equals(Contexto.RETORNO)) {
                            return (R) ret;
                        } else if (ret.v.ACadena().equals(Contexto.DETENER) && flujo) {
                            return (R) ret;
                        }
                    }
                }
            }
        }
        return (R) ret;
    }

    public R visit(final Selecciona n) {
        
        Simbolo exp_selec = (Simbolo)n.f2.accept(this); //expresion logica        
        NodeSequence ns =  n.f5; //nodeopcional}
        Bool b ;
        caso caso1 =  (caso) ns.nodes.get(0);
        NodeListOptional nop =  n.f6;
        boolean ejecuta_defecto =  true;
        boolean ejecuta_hasta =  false;
        Simbolo retorno =  new Simbolo("temp", "", new Texto("vacio", ""));
        nop.nodes.add(0,caso1);
        
        for(INode_usql node :  nop.nodes){
            caso c =  (caso) node;
            Simbolo exp_caso =  (Simbolo) c.f1.accept(this);
            b = (Bool)Operaciones_aritmeticas.OperacionIgualdad(exp_caso, exp_selec);
            if(b.ABool()){
                retorno = (Simbolo) c.accept(this);
                ejecuta_defecto =  false;
                ejecuta_hasta =  true;
            }else if(ejecuta_hasta){
                retorno = (Simbolo)c.accept(this);
            }
            if(retorno.v.ACadena().equals(Contexto.RETORNO)){
                return (R)retorno;
            }
            if(retorno.v.ACadena().equals(Contexto.DETENER)){
                retorno.v  = new Texto("vacio", "");
                break;
            }
        }
        if(n.f7.present() && ejecuta_defecto){
            NodeSequence ns_defecto =  (NodeSequence) n.f7.node;
            NodeListOptional nlo =  (NodeListOptional) ns_defecto.nodes.get(2);
            for(INode_usql node :  nlo.nodes){
                retorno  = (Simbolo)node.accept(this);
                if(retorno.v.ACadena().equals(Contexto.RETORNO)){
                    return (R)retorno;
                }
                if(retorno.v.ACadena().equals(Contexto.DETENER)){
                    retorno.v  = new Texto("vacio", "");
                    break;
                }
            }
        }                        
        return (R)retorno;
    }

    public R visit(final caso n) {
        Simbolo retorno  =  new Simbolo("temp", "", null);
        for(INode_usql node : n.f3.nodes){
            retorno = (Simbolo) node.accept(this);
            if(retorno.v.ACadena().equals(Contexto.RETORNO)){
                return (R)retorno;
            }
            if(retorno.v.ACadena().equals(Contexto.DETENER)){                
                return (R)retorno;
            }
        }
        return (R)retorno;
    }

    public R visit(final Para n) {
        Simbolo retorno = new Simbolo("temp", "", new Texto("", ""));
        n.f2.accept(this);
        Ent d  = this.global;
        Simbolo exp_l = (Simbolo) n.f3.accept(this);
        String varContro = n.f2.f1.tokenImage;
        Simbolo varControl = this.global.Buscar(varContro);
        if (varControl.v.Tipo.equals(Contexto.ENT)) {
            while (exp_l.v.ABool()) {
                for (INode_usql node : n.f8.nodes) {
                    retorno = (Simbolo) node.accept(this);
                    if (retorno.v.ACadena().equals(Contexto.RETORNO)) {
                        return (R) retorno;
                    }
                    if (retorno.v.ACadena().equals(Contexto.DETENER)) {                        
                        break;
                    }
                }
                if(retorno.v.ACadena().equals(Contexto.DETENER)){
                    retorno.v = new Texto("vacio", "");
                    break;
                }                                    
                int valor;
                Entero val;
                switch (n.f5.which) {
                    case 0:
                        valor =  varControl.v.AEntero() + 1;
                        val =  new Entero(Integer.toString(valor), varContro);
                        varControl.v = val;
                        break;
                    case 1:
                        valor =  varControl.v.AEntero() - 1;                        
                        val =  new Entero(Integer.toString(valor), varContro);
                        varControl.v = val;
                        break;
                }
                exp_l = (Simbolo) n.f3.accept(this);
            }
        }else{
            Debuger.Debug("Error la variable de contron del cilco para debe de ser de tipo entero...",false,null);
        }
        return (R) retorno;
    }

    public R visit(final Mientras n) {
        Simbolo retorno = new Simbolo("temporal", "", null);
        Simbolo exp_l = (Simbolo) n.f2.accept(this);
        while (((Simbolo) n.f2.accept(this)).v.ABool()) {
            for (INode_usql node : n.f5.nodes) {
                retorno = (Simbolo) node.accept(this);
                if (retorno.v.ACadena().equals(Contexto.RETORNO)) {
                    return (R) retorno;
                }
                if (retorno.v.ACadena().equals(Contexto.DETENER)) {
                    break;
                }
            }
            if (retorno.v.ACadena().equals(Contexto.DETENER)) {
                retorno.v = new Texto("vacio", "");
            }
        }
        return (R) retorno;
    }

    public R visit(final Detener n) {
        Simbolo detener =  new Simbolo("temp","", new Texto(Contexto.DETENER, Contexto.TEX));
        return (R)detener;
    }

    public R visit(final Imprimir n) {
        Simbolo impresion = (Simbolo) n.f2.accept(this);//expresion logica; 
        Debuger.Debug(null, false, impresion);        
        return (R)impresion;
    }

    public R visit(final Fecha n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final Fecha_hora n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final Contar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final Backup_dump n) {
        Simbolo retorno =  new Simbolo ("", "",new Texto("vacio", ""));
        
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        
        return (R)retorno;
    }

    public R visit(final Restaurar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        return nRes;
    }

}
