/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;
import java.util.*;
import Analizador_xml.*;
import Analizador_usql.*;
import proyecto.*;
import Entorno.*;
import Ejecucion_usql.*;

public class DepthFirstRetVisitor_usql<R> implements IRetVisitor<R> {

    public Ent levantado = new Ent(null);

    public R visit(final NodeChoice n) {
        final R nRes = n.choice.accept(this);
        return nRes;
    }

    public R visit(final NodeList n) {
        R nRes = null;
        for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
            @SuppressWarnings("unused")
            final R sRes = e.next().accept(this);
        }
        return nRes;
    }

    public R visit(final NodeListOptional n) {
        if (n.present()) {
            R nRes = null;
            for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
                @SuppressWarnings("unused")
                R sRes = e.next().accept(this);
            }
            return nRes;
        } else {
            return null;
        }
    }

    public R visit(final NodeOptional n) {
        if (n.present()) {
            final R nRes = n.node.accept(this);
            return nRes;
        } else {
            return null;
        }
    }

    public R visit(final NodeSequence n) {
        R nRes = null;
        for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
            @SuppressWarnings("unused")
            R subRet = e.next().accept(this);
        }
        return nRes;
    }

    public R visit(final NodeToken n) {
        R nRes = null;
        @SuppressWarnings("unused")
        final String tkIm = n.tokenImage;
        return nRes;
    }

    public R visit(final Inicio n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final listasentencias n) {
        R nRes = null;
        switch (n.f0.which) {
            case 0:
                //crear base de datos
                NodeSequence dd = (NodeSequence) n.f0.choice;
                NodeChoice choice = (NodeChoice) dd.nodes.get(1);
                switch (choice.which) {
                    case 0:
                        Instruccion_crear.CrearBase((crear_base) choice.choice);
                        break;
                    case 1:
                        Instruccion_crear.CrearTabla((crear_tabla) choice.choice);
                        break;
                    case 2:
                        Instruccion_crear.CrearObjeto((crear_objeto) choice.choice);
                        break;
                    case 3:
                        Instruccion_crear.CrearFunProc((crear_procedimiento) choice.choice);
                        break;
                    case 4:
                        Instruccion_crear.CrearFunProc((crear_funcion) choice.choice);
                        break;
                    case 5:
                        Instruccion_crear.CrearUsuario((crear_usuario) choice.choice);
                        break;
                }
                break;
            case 1:
                NodeSequence Usar = (NodeSequence) n.f0.choice;
                NodeToken Tusar = (NodeToken) Usar.nodes.get(1);
                String NombreBase = Tusar.tokenImage;
                Instruccion_usar.UsarBase(NombreBase);
                break;
            case 2:
                NodeSequence dd_alterar = (NodeSequence) n.f0.choice;
                NodeChoice choice_alterar = (NodeChoice) dd_alterar.nodes.get(1);
                switch (choice_alterar.which) {
                    case 0:
                        choice_alterar.choice.accept(this);
                        break;
                    case 1:
                        choice_alterar.choice.accept(this);
                        break;
                    case 2:
                        Instruccion_alterar.AlterarUsuario((Simbolo)choice_alterar.choice.accept(this));
                        break;
                    case 3:
                        break;
                }
                break;
            case 3:
                NodeSequence ddd_alterar = (NodeSequence) n.f0.choice;
                NodeChoice choice_eliminar = (NodeChoice) ddd_alterar.nodes.get(1);
                Simbolo choiceSimbolo = (Simbolo)choice_eliminar.choice.accept(this);
                switch(choice_eliminar.which){
                    case 0:
                        Instruccion_eliminar.EliminarUsuario(choiceSimbolo);
                        break;                        
                    case 1:
                        Instruccion_eliminar.EliminarTabla(choiceSimbolo);
                        break;
                    case 2:
                        Instruccion_eliminar.EliminarBd(choiceSimbolo);
                        break;
                    case 3: 
                        Instruccion_eliminar.EliminarObjeto(choiceSimbolo);
                        break;
                }
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
            case 7:
                break;
            case 8:
                //otorgar 
                INode_usql dd_otorgar = (INode_usql) n.f0.choice;                
                Instruccion_otorgar.OtorgarPermisos((Simbolo)dd_otorgar.accept(this));
                break;
            case 9:
                INode_usql dd_denegar = (INode_usql) n.f0.choice;                
                Instruccion_denegar.DenegarPermisos((Simbolo)dd_denegar.accept(this));
                break;
            case 10:
                break;
            case 11:
                break;
            case 12:
                break;
            case 13:
                break;
            case 14:
                break;
            case 15:
                break;
            case 16:
                break;
            case 17:
                break;
            case 18:
                break;
            case 19:
                break;
        }
        return nRes;
    }

    public R visit(final eliminar_usuario n) {                
        String identificadorUsuario = n.f1.tokenImage;
        Simbolo user  = new Simbolo(identificadorUsuario, identificadorUsuario, null);
        return (R)user;
    }

    public R visit(final eliminar_tabla n) {                
        String identificadorTabla = n.f1.tokenImage;
        Simbolo s =  new Simbolo(identificadorTabla, "", null);
        return (R)s;
    }

    public R visit(final eliminar_base n) {               
        String identificador = n.f1.tokenImage;
        Simbolo s =  new Simbolo(identificador, "", null);
        return (R)s;
    }

    public R visit(final eliminar_objeto n) {                
        String identificador = n.f1.tokenImage;
        Simbolo s =  new Simbolo(identificador, identificador, null);
        return (R)s;
    }

    public R visit(final alterar_usuario n) {                
        String nombreUsuario =  n.f1.tokenImage;      
        String claveUsuario = n.f5.tokenImage;
        Usuario_ent user =  new Usuario_ent(nombreUsuario, claveUsuario);
        Simbolo sreturn =  new Simbolo(nombreUsuario, "", user);
        return (R)sreturn;
    }

    public R visit(final alterar_tabla n) {
        n.f0.accept(this);
        String identificador = n.f1.tokenImage;//identificador
        NodeChoice no = n.f2;
        switch (no.which) {
            case 0:
                Instruccion_alterar.AgregarTabla((agregar_tabla) no.choice, identificador);
                break;
            case 1:
                Instruccion_alterar.QuitarTabla((quitar) no.choice, identificador);
                break;
        }
        return null;
    }

    public R visit(final alterar_objeto n) {
        n.f0.accept(this);
        String identificador = n.f1.tokenImage;//identificador
        NodeChoice no = n.f2;
        switch (no.which) {
            case 0:
                Instruccion_alterar.AgregarObjeto((agregar_objeto) no.choice, identificador);
                break;
            case 1:
                Instruccion_alterar.QuitarObjeto((quitar)no.choice, identificador);
                break;
        }
        return null;
    }

    public R visit(final agregar_tabla n) {
        R nRes = null;
        Tabla t = new Tabla("");
        NodeSequence ns = n.f2;
        Simbolo primerAtributo = (Simbolo) ns.nodes.get(0).accept(this);
        t.valores.add(primerAtributo);
        if (n.f3.present()) {
            for (int i = 0; i < n.f3.size(); i++) {
                NodeSequence ns1 = (NodeSequence) n.f3.nodes.get(i);
                Simbolo siguienteAtributo = (Simbolo) ns1.nodes.get(1).accept(this);
                t.valores.add(siguienteAtributo);
            }
        }
        Simbolo NuevosAtributos = new Simbolo("temp", "", t);
        return (R) NuevosAtributos;
    }

    public R visit(final quitar n) {
        Tabla t = new Tabla("");
        Simbolo primerAtributo = new Simbolo(n.f1.tokenImage, "", null);
        t.valores.add(primerAtributo);
        if (n.f2.present()) {
            for (INode_usql n1 : n.f2.nodes) {
                NodeSequence ns = (NodeSequence) n1;
                NodeToken tok = (NodeToken) ns.nodes.get(1);
                Simbolo siguienteAtributo = new Simbolo(tok.tokenImage, "", null);
                t.valores.add(siguienteAtributo);
            }
        }
        Simbolo tablaTemporal = new Simbolo("temporal", "", t);
        return (R) tablaTemporal;
    }

    public R visit(final agregar_objeto n) {
        Tabla val =  new Tabla("");        
        NodeSequence ns = n.f2;
        Simbolo primerComponente = (Simbolo) ns.nodes.get(0).accept(this);
        val.valores.add(primerComponente);
        if (n.f3.present()) {
            for (int i = 0; i < n.f3.size(); i++) {
                NodeSequence ns1 = (NodeSequence) n.f3.nodes.get(i);
                Simbolo siguienteComponente = (Simbolo) ns1.nodes.get(1).accept(this);
                val.valores.add(siguienteComponente);
            }
        }
        Simbolo temp =  new Simbolo("temporal", "", val);
        return (R)temp;
    }

    public R visit(final crear_base n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final crear_tabla n) {
        R nRes = null;
        Simbolo s;
        Tabla t = new Tabla("");
        t.permisos = "";
        n.f2.accept(this);
        Simbolo patri = (Simbolo) n.f3.nodes.get(0).accept(this); //primer atributo nodesequence
        t.valores.add(patri);
        NodeListOptional nlo = n.f4; //lista de otros atrib
        if (nlo.present()) {
            for (int c = 0; c < nlo.size(); c++) {
                NodeSequence ns = (NodeSequence) nlo.nodes.get(c);
                Simbolo otrib = (Simbolo) ns.nodes.get(1).accept(this);
                if (Contexto.ExisteColumna(t.valores, otrib.nombre)) {
                    Debuger.Debug("La tabla " + n.f1.tokenImage + " ya tiene una columna con el nombre " + otrib.nombre);
                } else {
                    t.valores.add(otrib);
                }
            }
        }
        t.Tipo = n.f1.tokenImage;
        s = new Simbolo(n.f1.tokenImage, "", t);
        nRes = (R) s;
        return nRes;
    }

    public R visit(final lista_atributos n) {
        R nRes = null;
        Columna c = new Columna(null, "");
        Simbolo tipo = (Simbolo) n.f0.accept(this);
        Simbolo colum = new Simbolo(n.f1.tokenImage, tipo.tipo, null);
        if (n.f2.present()) {
            NodeList nl = (NodeList) n.f2.node;
            for (int i = 0; i < nl.size(); i++) {
                Simbolo complemento = (Simbolo) nl.nodes.get(i).accept(this);
                c.atributos.add(complemento);
            }
        }
        colum.v = c;
        nRes = (R) colum;
        return nRes;
    }

    public R visit(final tipo n) {
        R nRes = null;
        Simbolo s = null;
        switch (n.f0.which) {
            case 0:
                s = new Simbolo("", Contexto.TEX, null);
                break;
            case 1:
                s = new Simbolo("", Contexto.ENT, null);
                break;
            case 2:
                s = new Simbolo("", Contexto.DOB, null);
                break;
            case 3:
                s = new Simbolo("", Contexto.BOl, null);
                break;
            case 4:
                s = new Simbolo("", Contexto.DAT, null);
                break;
            case 5:
                s = new Simbolo("", Contexto.DATH, null);
                break;
            case 6:
                NodeToken nt = (NodeToken) n.f0.choice;
                s = new Simbolo("", nt.tokenImage, null);
                break;
        }
        nRes = (R) s;
        return nRes;
    }

    public R visit(final complemento_campo n) {
        R nRes = null;
        Simbolo s = null;
        switch (n.f0.which) {
            case 0:
                s = new Simbolo("nulo", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 1:
                s = new Simbolo("nulo", Contexto.BOl, new Bool("0", Contexto.BOl));
                break;
            case 2:
                s = new Simbolo("prim", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 3:
                NodeSequence ns = (NodeSequence) n.f0.choice;
                NodeToken tk = (NodeToken) ns.nodes.get(1);
                String referencia = tk.tokenImage;
                if (!levantado.existe(referencia)) {
                    Debuger.Debug("Error la tabla a la que se hace referencia no existe...");
                    Debuger.Debug("Objeto no encontrado... " + referencia);
                    return null;
                }
                s = new Simbolo("for", Contexto.BOl, new Bool(referencia, Contexto.BOl));
                break;
            case 4:
                s = new Simbolo("auto", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
            case 5:
                s = new Simbolo("unico", Contexto.BOl, new Bool("1", Contexto.BOl));
                break;
        }
        nRes = (R) s;
        return nRes;
    }

    public R visit(final crear_objeto n) {
        Objeto obj = new Objeto("");
        n.f1.accept(this); //id
        Simbolo primero = (Simbolo) n.f3.accept(this); //primer atributo
        obj.valor.insertar(primero.nombre, primero);
        n.f4.accept(this);
        NodeListOptional nlo = n.f4; //lista de otros atrib
        if (nlo.present()) {
            for (int c = 0; c < nlo.size(); c++) {
                NodeSequence ns = (NodeSequence) nlo.nodes.get(c);
                Simbolo otrib = (Simbolo) ns.nodes.get(1).accept(this);
                obj.valor.insertar(otrib.nombre, otrib);
            }
        }
        obj.Tipo = n.f1.tokenImage;
        Simbolo nres = new Simbolo(n.f1.tokenImage, n.f1.tokenImage, obj);
        return (R) nres;
    }

    public R visit(final lista_componentes n) {
        Simbolo tipo = (Simbolo) n.f0.accept(this); //tipo
        Simbolo s = new Simbolo(n.f1.tokenImage, tipo.tipo, null);
        return (R) s;
    }

    public R visit(final crear_procedimiento n) {
        String identificador = n.f1.tokenImage; //identificador                                 
        DepthFirstVoidVisitor ContenidoInstrucciones = new DepthFirstVoidVisitor();
        n.f6.accept(ContenidoInstrucciones); //instrucciones       
        String instrucciones = ContenidoInstrucciones.instrucciones.toString();
        FuncionProc func = new FuncionProc(n.f6);
        if (n.f3.present()) {
            NodeSequence ns = (NodeSequence) n.f3.node;
            lista_parametros parametor = (lista_parametros) ns.nodes.get(0);
            func.parametros.add((Simbolo) parametor.accept(this));
            NodeListOptional nlo = (NodeListOptional) ns.nodes.get(1);
            for (int i = 0; i < nlo.size(); i++) {
                NodeSequence ns1 = (NodeSequence) nlo.nodes.get(i);
                Simbolo param = (Simbolo) ns1.nodes.get(1).accept(this);
                func.parametros.add(param);
            }
        }
        func.permisos = "\"\"";
        func.src = instrucciones;
        Simbolo nres = new Simbolo(identificador, "", func);
        return (R) nres;
    }

    public R visit(final lista_parametros n) {
        R nRes = null;
        Simbolo tipo = (Simbolo) n.f0.accept(this);
        String nombre = n.f1.tokenImage;
        Simbolo param = new Simbolo(nombre, tipo.tipo, null);
        return (R) param;
    }

    public R visit(final crear_funcion n) {
        String identificador = n.f1.tokenImage; //identificador                        
        Simbolo tipo_func = (Simbolo) n.f5.accept(this);
        DepthFirstVoidVisitor ContenidoInstrucciones = new DepthFirstVoidVisitor();
        n.f7.accept(ContenidoInstrucciones); //instrucciones       
        String instrucciones = ContenidoInstrucciones.instrucciones.toString();
        FuncionProc func = new FuncionProc(n.f7);
        if (n.f3.present()) {
            NodeSequence ns = (NodeSequence) n.f3.node;
            lista_parametros parametor = (lista_parametros) ns.nodes.get(0);
            func.parametros.add((Simbolo) parametor.accept(this));
            NodeListOptional nlo = (NodeListOptional) ns.nodes.get(1);
            for (int i = 0; i < nlo.size(); i++) {
                NodeSequence ns1 = (NodeSequence) nlo.nodes.get(i);
                Simbolo param = (Simbolo) ns1.nodes.get(1).accept(this);
                func.parametros.add(param);
            }
        }
        func.permisos = "\"\"";
        func.src = instrucciones;
        func.Tipo = tipo_func.tipo;
        Simbolo nres = new Simbolo(identificador, tipo_func.tipo, func);
        return (R) nres;
    }

    public R visit(final lista_sentencias_p n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final Retorno n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final crear_usuario n) {
        Usuario_ent us = new Usuario_ent(n.f1.tokenImage, n.f5.tokenImage);
        Simbolo s = new Simbolo(us.nombre, "", us);
        return (R) s;
    }

    public R visit(final insertar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        return nRes;
    }

    public R visit(final lista_expresion n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final expresion n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final g n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final t n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final f n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final h n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final exp_relacional n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final exp_logica n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final exp_or n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final exp_and n) {
        R nRes = null;
        n.f0.accept(this);
        return nRes;
    }

    public R visit(final actualizar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        n.f8.accept(this);
        n.f9.accept(this);
        n.f10.accept(this);
        n.f11.accept(this);
        n.f12.accept(this);
        n.f13.accept(this);
        return nRes;
    }

    public R visit(final borrar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        return nRes;
    }

    public R visit(final seleccionar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        return nRes;
    }

    public R visit(final otorgar n) { 
        Tabla val =  new Tabla("");
        String idUsuario = n.f2.tokenImage;
        String idBd = n.f4.tokenImage;
        NodeToken tok =  (NodeToken) n.f6.choice;        
        String queObjeto =  tok.tokenImage;
        Simbolo bd =  new Simbolo(idBd,"",null);
        Simbolo usuario =  new Simbolo(idUsuario, idBd, null);
        Simbolo objeto =  new Simbolo(queObjeto, queObjeto, null);
        val.valores.add(bd);
        val.valores.add(usuario);
        val.valores.add(objeto);
        Simbolo otorgar =  new Simbolo("otorgar", "", val);
        return (R)otorgar;
    }

    public R visit(final denegar n) {
        Tabla val =  new Tabla("");
        String idUsuario = n.f2.tokenImage;
        String idBd = n.f4.tokenImage;
        NodeToken tok =  (NodeToken) n.f6.choice;        
        String queObjeto =  tok.tokenImage;
        Simbolo bd =  new Simbolo(idBd,"",null);
        Simbolo usuario =  new Simbolo(idUsuario, idBd, null);
        Simbolo objeto =  new Simbolo(queObjeto, queObjeto, null);
        val.valores.add(bd);
        val.valores.add(usuario);
        val.valores.add(objeto);
        Simbolo otorgar =  new Simbolo("otorgar", "", val);
        return (R)otorgar;        
    }

    public R visit(final Declarar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final asignacion n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final Si n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        return nRes;
    }

    public R visit(final Selecciona n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        n.f8.accept(this);
        return nRes;
    }

    public R visit(final caso n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        return nRes;
    }

    public R visit(final Para n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        n.f8.accept(this);
        n.f9.accept(this);
        return nRes;
    }

    public R visit(final Mientras n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        return nRes;
    }

    public R visit(final Detener n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        return nRes;
    }

    public R visit(final Imprimir n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final Fecha n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final Fecha_hora n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        return nRes;
    }

    public R visit(final Contar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final Backup_dump n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        return nRes;
    }

    public R visit(final Restaurar n) {
        R nRes = null;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        return nRes;
    }

}
