/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;
import java.util.*;
import Analizador_xml.*;
import Analizador_usql.*;
import proyecto.*;
import Entorno.*;
import Ejecucion_usql.*;

public class DepthFirstVoidVisitor implements IVoidVisitor {

    public StringBuilder instrucciones = new StringBuilder();

  public void visit(final NodeChoice n) {
    n.choice.accept(this);
    return;
  }

  public void visit(final NodeList n) {
    for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
      e.next().accept(this);
    }
    return;
  }

  public void visit(final NodeListOptional n) {
    if (n.present()) {
      for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
        e.next().accept(this);
        }
      return;
    } else
      return;
  }

  public void visit(final NodeOptional n) {
    if (n.present()) {
      n.node.accept(this);
      return;
    } else
    return;
  }

  public void visit(final NodeSequence n) {
    for (final Iterator<INode_usql> e = n.elements(); e.hasNext();) {
      e.next().accept(this);
    }
    return;
  }

  public void visit(final NodeToken n) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    this.instrucciones.append(" ").append(tkIm).append(" ");
    return;
  }

  public void visit(final Inicio n) {
    n.f0.accept(this);
  }

  public void visit(final listasentencias n) {    
    switch (n.f0.which) {
            case 0:
                //crear base de datos
                NodeSequence dd = (NodeSequence) n.f0.choice;
                NodeChoice choice = (NodeChoice) dd.nodes.get(1);                
                this.instrucciones.append("crear");
                switch(choice.which){
                    case 0:
                        choice.choice.accept(this);
                        break;
                    case 1:
                        choice.choice.accept(this);
                        break;
                    case 2:
                        choice.choice.accept(this);
                        break;
                    case 3:
                        choice.choice.accept(this);
                        break;
                    case 4:
                        choice.choice.accept(this);
                        break;
                    case 5:
                        choice.choice.accept(this);
                        break;
                }
                break;
            case 1:
                n.f0.choice.accept(this);
                break;
            case 2:
                n.f0.choice.accept(this);
                break;
            case 3:
                n.f0.choice.accept(this);
                break;
            case 4:
                n.f0.choice.accept(this);
                break;
            case 5:
                n.f0.choice.accept(this);
                break;
            case 6:
                n.f0.choice.accept(this);
                break;
            case 7:
                n.f0.choice.accept(this);
                break;
            case 8:
                n.f0.choice.accept(this);
                break;
            case 9:
                n.f0.choice.accept(this);
                break;
            case 10:
                n.f0.choice.accept(this);
                break;
            case 11:
                n.f0.choice.accept(this);
                break;
            case 12:
                n.f0.choice.accept(this);
                break;
            case 13:
                n.f0.choice.accept(this);
                break;
            case 14:
                n.f0.choice.accept(this);
                break;
            case 15:
                n.f0.choice.accept(this);
                break;                
            case 16:
                n.f0.choice.accept(this);
                break;
            case 17:
                n.f0.choice.accept(this);
                break;
            case 18:
                n.f0.choice.accept(this);
                break;
            case 19:
                n.f0.choice.accept(this);
                break;
        }
  }

  public void visit(final eliminar_usuario n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final eliminar_tabla n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final eliminar_base n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final eliminar_objeto n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final alterar_usuario n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
  }

  public void visit(final alterar_tabla n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final alterar_objeto n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final agregar_tabla n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final quitar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final agregar_objeto n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final crear_base n) {
    
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final crear_tabla n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
  }

  public void visit(final lista_atributos n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final tipo n) {
    n.f0.accept(this);
  }

  public void visit(final complemento_campo n) {
    n.f0.accept(this);
  }

  public void visit(final crear_objeto n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
  }

  public void visit(final lista_componentes n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final crear_procedimiento n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
  }

  public void visit(final lista_parametros n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final crear_funcion n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    n.f8.accept(this);
  }

  public void visit(final lista_sentencias_p n) {
    n.f0.accept(this);
  }

  public void visit(final Retorno n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final crear_usuario n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
  }

  public void visit(final insertar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
  }

  public void visit(final lista_expresion n) {
    n.f0.accept(this);
  }

  public void visit(final expresion n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final g n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final t n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final f n) {
    n.f0.accept(this);
  }

  public void visit(final h n) {
    n.f0.accept(this);
  }

  public void visit(final exp_relacional n) {
    n.f0.accept(this);
  }

  public void visit(final exp_logica n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final exp_or n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final exp_and n) {
    n.f0.accept(this);
  }

  public void visit(final actualizar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    n.f8.accept(this);
    n.f9.accept(this);
    n.f10.accept(this);
    n.f11.accept(this);
    n.f12.accept(this);
    n.f13.accept(this);
  }

  public void visit(final borrar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
  }

  public void visit(final seleccionar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
  }

  public void visit(final otorgar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
  }

  public void visit(final denegar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
  }

  public void visit(final Declarar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final asignacion n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final Si n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
  }

  public void visit(final Selecciona n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    n.f8.accept(this);
  }

  public void visit(final caso n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
  }

  public void visit(final Para n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    n.f8.accept(this);
    n.f9.accept(this);
  }

  public void visit(final Mientras n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
  }

  public void visit(final Detener n) {
    n.f0.accept(this);
    n.f1.accept(this);
  }

  public void visit(final Imprimir n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final Fecha n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final Fecha_hora n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
  }

  public void visit(final Contar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final Backup_dump n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
  }

  public void visit(final Restaurar n) {
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
  }

}
