/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Inicio n);

  public R visit(final listasentencias n);

  public R visit(final eliminar_usuario n);

  public R visit(final eliminar_tabla n);

  public R visit(final eliminar_base n);

  public R visit(final eliminar_objeto n);

  public R visit(final alterar_usuario n);

  public R visit(final alterar_tabla n);

  public R visit(final alterar_objeto n);

  public R visit(final agregar_tabla n);

  public R visit(final quitar n);

  public R visit(final agregar_objeto n);

  public R visit(final crear_base n);

  public R visit(final crear_tabla n);

  public R visit(final lista_atributos n);

  public R visit(final tipo n);

  public R visit(final complemento_campo n);

  public R visit(final crear_objeto n);

  public R visit(final lista_componentes n);

  public R visit(final crear_procedimiento n);

  public R visit(final lista_parametros n);

  public R visit(final crear_funcion n);

  public R visit(final lista_sentencias_p n);

  public R visit(final Retorno n);

  public R visit(final crear_usuario n);

  public R visit(final insertar n);

  public R visit(final lista_expresion n);

  public R visit(final expresion n);

  public R visit(final g n);

  public R visit(final t n);

  public R visit(final f n);

  public R visit(final h n);

  public R visit(final exp_relacional n);

  public R visit(final exp_logica n);

  public R visit(final exp_or n);

  public R visit(final exp_and n);

  public R visit(final actualizar n);

  public R visit(final borrar n);

  public R visit(final seleccionar n);

  public R visit(final otorgar n);

  public R visit(final denegar n);

  public R visit(final Declarar n);

  public R visit(final asignacion n);

  public R visit(final Si n);

  public R visit(final Selecciona n);

  public R visit(final caso n);

  public R visit(final Para n);

  public R visit(final Mientras n);

  public R visit(final Detener n);

  public R visit(final Imprimir n);

  public R visit(final Fecha n);

  public R visit(final Fecha_hora n);

  public R visit(final Contar n);

  public R visit(final Backup_dump n);

  public R visit(final Restaurar n);

}
