/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Inicio n, final A argu);

  public R visit(final listasentencias n, final A argu);

  public R visit(final eliminar_usuario n, final A argu);

  public R visit(final eliminar_tabla n, final A argu);

  public R visit(final eliminar_base n, final A argu);

  public R visit(final eliminar_objeto n, final A argu);

  public R visit(final alterar_usuario n, final A argu);

  public R visit(final alterar_tabla n, final A argu);

  public R visit(final alterar_objeto n, final A argu);

  public R visit(final agregar_tabla n, final A argu);

  public R visit(final quitar n, final A argu);

  public R visit(final agregar_objeto n, final A argu);

  public R visit(final crear_base n, final A argu);

  public R visit(final crear_tabla n, final A argu);

  public R visit(final lista_atributos n, final A argu);

  public R visit(final tipo n, final A argu);

  public R visit(final complemento_campo n, final A argu);

  public R visit(final crear_objeto n, final A argu);

  public R visit(final lista_componentes n, final A argu);

  public R visit(final crear_procedimiento n, final A argu);

  public R visit(final lista_parametros n, final A argu);

  public R visit(final crear_funcion n, final A argu);

  public R visit(final lista_sentencias_p n, final A argu);

  public R visit(final Retorno n, final A argu);

  public R visit(final crear_usuario n, final A argu);

  public R visit(final insertar n, final A argu);

  public R visit(final lista_expresion n, final A argu);

  public R visit(final expresion n, final A argu);

  public R visit(final g n, final A argu);

  public R visit(final t n, final A argu);

  public R visit(final f n, final A argu);

  public R visit(final h n, final A argu);

  public R visit(final exp_relacional n, final A argu);

  public R visit(final exp_logica n, final A argu);

  public R visit(final exp_or n, final A argu);

  public R visit(final exp_and n, final A argu);

  public R visit(final actualizar n, final A argu);

  public R visit(final borrar n, final A argu);

  public R visit(final seleccionar n, final A argu);

  public R visit(final otorgar n, final A argu);

  public R visit(final denegar n, final A argu);

  public R visit(final Declarar n, final A argu);

  public R visit(final asignacion n, final A argu);

  public R visit(final Si n, final A argu);

  public R visit(final Selecciona n, final A argu);

  public R visit(final caso n, final A argu);

  public R visit(final Para n, final A argu);

  public R visit(final Mientras n, final A argu);

  public R visit(final Detener n, final A argu);

  public R visit(final Imprimir n, final A argu);

  public R visit(final Fecha n, final A argu);

  public R visit(final Fecha_hora n, final A argu);

  public R visit(final Contar n, final A argu);

  public R visit(final Backup_dump n, final A argu);

  public R visit(final Restaurar n, final A argu);

}
