/* Generated by JTB 1.4.4 */
package visitorxml;

import arbolxml.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Inicio n, final A argu);

  public R visit(final lista_xml n, final A argu);

  public R visit(final usuarioxml n, final A argu);

  public R visit(final procedimiento n, final A argu);

  public R visit(final proc n, final A argu);

  public R visit(final objeto n, final A argu);

  public R visit(final obj n, final A argu);

  public R visit(final Db n, final A argu);

  public R visit(final lista_db n, final A argu);

  public R visit(final Tablaxml n, final A argu);

  public R visit(final lista_row n, final A argu);

  public R visit(final atributo n, final A argu);

}
