/* Generated by JTB 1.4.4 */
package visitorxml;

import arbolxml.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Inicio n);

  public R visit(final lista_xml n);

  public R visit(final row n);

  public R visit(final usuarioxml n);

  public R visit(final procedimiento n);

  public R visit(final proc n);

  public R visit(final objeto n);

  public R visit(final obj n);

  public R visit(final Db n);

  public R visit(final lista_db n);

  public R visit(final Tablaxml n);

  public R visit(final lista_row n);

  public R visit(final reg n);

  public R visit(final atributo n);

}
