/* Generated by JTB 1.4.4 */
package visitorxml;

import arbolxml.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);


  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Inicio n, final A argu);

  public void visit(final lista_xml n, final A argu);

  public void visit(final row n, final A argu);

  public void visit(final usuarioxml n, final A argu);

  public void visit(final procedimiento n, final A argu);

  public void visit(final proc n, final A argu);

  public void visit(final objeto n, final A argu);

  public void visit(final obj n, final A argu);

  public void visit(final Db n, final A argu);

  public void visit(final lista_db n, final A argu);

  public void visit(final Tablaxml n, final A argu);

  public void visit(final lista_row n, final A argu);

  public void visit(final reg n, final A argu);

  public void visit(final atributo n, final A argu);

}
