/* Generated by JTB 1.4.4 */
package visitorxml;

import arbolxml.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final Inicio n);

  public void visit(final lista_xml n);

  public void visit(final usuarioxml n);

  public void visit(final procedimiento n);

  public void visit(final proc n);

  public void visit(final objeto n);

  public void visit(final obj n);

  public void visit(final Db n);

  public void visit(final lista_db n);

  public void visit(final Tablaxml n);

  public void visit(final lista_row n);

  public void visit(final atributo n);

}
