/* Generated By:JavaCC: Do not edit this line. PlyParserConstants.java */
package Analizador_ply;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PlyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int VERDADERO = 8;
  /** RegularExpression Id. */
  int FALSO = 9;
  /** RegularExpression Id. */
  int S_NUMBERO = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DATE = 13;
  /** RegularExpression Id. */
  int HORA = 14;
  /** RegularExpression Id. */
  int DIGITO = 15;
  /** RegularExpression Id. */
  int K_prueba = 16;
  /** RegularExpression Id. */
  int K_dospuntos = 17;
  /** RegularExpression Id. */
  int K_coma = 18;
  /** RegularExpression Id. */
  int K_ciz = 19;
  /** RegularExpression Id. */
  int K_cder = 20;
  /** RegularExpression Id. */
  int K_igm = 21;
  /** RegularExpression Id. */
  int S_IDENTIFICADOR = 22;
  /** RegularExpression Id. */
  int LETRA = 23;
  /** RegularExpression Id. */
  int ESPECIAL = 24;
  /** RegularExpression Id. */
  int CADENA_LITERAL = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"1\"",
    "\"0\"",
    "<S_NUMBERO>",
    "<FLOAT>",
    "<INTEGER>",
    "<DATE>",
    "<HORA>",
    "<DIGITO>",
    "\"prueba\"",
    "\":\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"=>\"",
    "<S_IDENTIFICADOR>",
    "<LETRA>",
    "<ESPECIAL>",
    "<CADENA_LITERAL>",
  };

}
