/* Generated By:JavaCC: Do not edit this line. UsqlParserTokenManager.java */
package Analizador_usql;
import java.io.FileNotFoundException;
import syntaxtree.*;

/** Token Manager. */
public class UsqlParserTokenManager implements UsqlParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x300L) != 0L)
            return 22;
         if ((active0 & 0xffcff580003f0000L) != 0L || (active1 & 0x3fffbffffL) != 0L)
         {
            jjmatchedKind = 100;
            return 38;
         }
         return -1;
      case 1:
         if ((active1 & 0x20031e104L) != 0L)
            return 38;
         if ((active0 & 0xffcff580003f0000L) != 0L || (active1 & 0x1ffca1efbL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return 38;
         }
         return -1;
      case 2:
         if ((active0 & 0xffcfd580003f0000L) != 0L || (active1 & 0x1fffb7d7bL) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 2;
            return 38;
         }
         if ((active1 & 0x280L) != 0L)
            return 38;
         if ((active0 & 0x200000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0x800100000390000L) != 0L || (active1 & 0x490100L) != 0L)
            return 38;
         if ((active0 & 0x200000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xf7cfc58000060000L) != 0L || (active1 & 0x1ffb27c7bL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 3;
            }
            return 38;
         }
         return -1;
      case 4:
         if ((active0 & 0x2048000000000L) != 0L || (active1 & 0x6000400L) != 0L)
            return 38;
         if ((active0 & 0x200000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x10000000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 4;
            }
            return 13;
         }
         if ((active0 & 0xf7cdc00000260000L) != 0L || (active1 & 0x1f9b2787bL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 4;
            }
            return 38;
         }
         return -1;
      case 5:
         if ((active0 & 0x1810000000000L) != 0L || (active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 5;
            return 13;
         }
         if ((active0 & 0xb7c8400000220000L) != 0L || (active1 & 0x1e1b2786bL) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 5;
            return 38;
         }
         if ((active0 & 0x4004000000040000L) != 0L || (active1 & 0x18000010L) != 0L)
            return 38;
         if ((active0 & 0x200000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x1810000000000L) != 0L || (active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 6;
            return 13;
         }
         if ((active0 & 0xb3c0000000020000L) != 0L || (active1 & 0x100302840L) != 0L)
            return 38;
         if ((active0 & 0x200000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x408400000200000L) != 0L || (active1 & 0xe182502bL) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 6;
            return 38;
         }
         return -1;
      case 7:
         if ((active0 & 0x400000000200000L) != 0L || (active1 & 0x61805003L) != 0L)
            return 38;
         if ((active0 & 0x1810000000000L) != 0L || (active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 7;
            return 13;
         }
         if ((active0 & 0x8400000000000L) != 0L || (active1 & 0x80020028L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 7;
            return 38;
         }
         return -1;
      case 8:
         if ((active0 & 0x8400000000000L) != 0L || (active1 & 0x20028L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 8;
            return 38;
         }
         if ((active1 & 0x80000000L) != 0L)
            return 38;
         if ((active0 & 0x1810000000000L) != 0L || (active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 8;
            return 13;
         }
         return -1;
      case 9:
         if ((active0 & 0x1800000000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 9;
            }
            return 13;
         }
         if ((active1 & 0x20028L) != 0L)
            return 38;
         if ((active0 & 0x10000000000L) != 0L || (active1 & 0x4000000L) != 0L)
            return 13;
         if ((active0 & 0x8400000000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 9;
            }
            return 38;
         }
         return -1;
      case 10:
         if ((active1 & 0x20L) != 0L)
            return 38;
         if ((active0 & 0x8400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 10;
            return 38;
         }
         if ((active0 & 0x1800000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 10;
            return 13;
         }
         return -1;
      case 11:
         if ((active0 & 0x8400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 11;
            return 38;
         }
         if ((active0 & 0x1800000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 11;
            return 13;
         }
         return -1;
      case 12:
         if ((active0 & 0x8000000000000L) != 0L)
            return 38;
         if ((active0 & 0x1000000000000L) != 0L)
            return 13;
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 12;
            return 13;
         }
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 12;
            return 38;
         }
         return -1;
      case 13:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 13;
            return 38;
         }
         if ((active0 & 0x800000000000L) != 0L)
            return 13;
         return -1;
      case 14:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 14;
            return 38;
         }
         return -1;
      case 15:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 15;
            return 38;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 36;
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x800000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 37);
      case 41:
         return jjStopAtPos(0, 38);
      case 42:
         return jjStopAtPos(0, 24);
      case 43:
         jjmatchedKind = 22;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000000L);
      case 44:
         return jjStopAtPos(0, 43);
      case 45:
         jjmatchedKind = 23;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000000L);
      case 46:
         return jjStopAtPos(0, 104);
      case 47:
         return jjStopAtPos(0, 25);
      case 48:
         return jjStartNfaWithStates_0(0, 9, 22);
      case 49:
         return jjStartNfaWithStates_0(0, 8, 22);
      case 58:
         return jjStopAtPos(0, 82);
      case 59:
         return jjStopAtPos(0, 41);
      case 60:
         jjmatchedKind = 30;
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L);
      case 61:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 62:
         jjmatchedKind = 31;
         return jjMoveStringLiteralDfa1_0(0x200000000L, 0x0L);
      case 94:
         return jjStopAtPos(0, 26);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x3000400000000000L, 0x88L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x10000080000L, 0x10000010L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x8200008000000000L, 0x48080000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x340000L, 0x200306500L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x5L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x6000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x1000002L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1800000000000L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x300000000000L, 0x0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x840L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x408000000000000L, 0x401200L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x80000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x38020L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000010000L, 0x0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x902000000000000L, 0x20000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000L);
      case 123:
         return jjStopAtPos(0, 52);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x400000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 53);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 35);
         break;
      case 43:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 105);
         break;
      case 45:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 106);
         break;
      case 61:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 29);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400050000300000L, active1, 0x110480000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      case 69:
      case 101:
         if ((active1 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000010000L, active1, 0x86327120L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000000L, active1, 0L);
      case 73:
      case 105:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x810000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x1001800000000000L, active1, 0x1L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000L);
      case 78:
      case 110:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(1, 66, 38);
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000020000L, active1, 0x2L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x2002000000c0000L, active1, 0x48000610L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x8008000000000L, active1, 0x40L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x900000000000000L, active1, 0x20000080L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4040500000000000L, active1, 0L);
      case 124:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 34);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x801800000000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L);
      case 67:
      case 99:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 71, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x16004000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0x800000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4002000000000000L, active1, 0x1L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x200100000000000L, active1, 0x100020020L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x40000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0x8012400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000080000L, active1, 0x800L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20000000L);
      case 82:
      case 114:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 38);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0x401010L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x400010000000000L, active1, 0x80080102L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x1080400000320000L, active1, 0x200008L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000040000L, active1, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 86, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x100008000000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000040000L, active1, 0L);
      case 67:
      case 99:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x4a000000000000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x3004010000220000L, active1, 0x322062L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x6000000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10000000L);
      case 76:
      case 108:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L, active1, 0x20004000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1001L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L, active1, 0x800000L);
      case 79:
      case 111:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 38);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 80, 38);
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 83, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x280400000000000L, active1, 0x100000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40000000L);
      case 82:
      case 114:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 59, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000810L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000000L, active1, 0L);
      case 84:
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 38);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000000L, active1, 0x88000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L, active1, 0L);
      case 65:
      case 97:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 38);
         else if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0x8c004018L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000000L, active1, 0x120020L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20000000L);
      case 69:
      case 101:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 74, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x9800000000000L, active1, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000020000L, active1, 0x2800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8040400000000000L, active1, 0x1001001L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L, active1, 0x40000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200040L);
      case 79:
      case 111:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 38);
         break;
      case 82:
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 38);
         return jjMoveStringLiteralDfa5_0(active0, 0x1180000000000000L, active1, 0x100000002L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000200000L, active1, 0x800000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L, active1, 0x10000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000000000L, active1, 0x4000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0xb200000000000000L, active1, 0x2840L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x20020L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x8010000000000L, active1, 0L);
      case 69:
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L, active1, 0x140200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000200000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000L, active1, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x80400000000000L, active1, 0x1L);
      case 79:
      case 111:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0x440000000000000L, active1, 0L);
      case 80:
      case 112:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 92, 38);
         break;
      case 82:
      case 114:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 62, 38);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 38);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 91, 38);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x804000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100002L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0xa0000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L, active1, 0x804003L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L, active1, 0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L, active1, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0x1020028L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L, active1, 0x20000000L);
      case 78:
      case 110:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 54, 38);
         break;
      case 79:
      case 111:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(6, 45);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 38);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 38);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 84, 38);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 38);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 38);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 38);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 61, 38);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 63, 38);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 70, 38);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 75, 38);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 77, 38);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 85, 38);
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0x80000000L);
      case 83:
      case 115:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(6, 96, 38);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80000000L);
      case 68:
      case 100:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 58, 38);
         break;
      case 69:
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(7, 21, 38);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L, active1, 0L);
      case 79:
      case 111:
         if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 94, 38);
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000L, active1, 0x4020020L);
      case 80:
      case 112:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 93, 38);
         break;
      case 82:
      case 114:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(7, 64, 38);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 65, 38);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 78, 38);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(7, 88, 38);
         return jjMoveStringLiteralDfa8_0(active0, 0xc00000000000L, active1, 0L);
      case 83:
      case 115:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(7, 76, 38);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 87, 38);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L, active1, 0L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x8L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x8800000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20020L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(8, 95, 38);
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000L, active1, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 9;
         }
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(9, 90, 13);
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000L, active1, 0x20L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0xc00000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(9, 67, 38);
         break;
      case 83:
      case 115:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 40, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x9000000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(10, 69, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 48, 13);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000000000L);
      case 79:
      case 111:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 51, 38);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 47, 13);
         return jjMoveStringLiteralDfa14_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(16, 46, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 38;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 38:
               case 13:
                  if ((0x3ff001800000000L & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAdd(13);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 46)
                     jjCheckNAdd(20);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(21);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(15, 16);
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 2;
                  if (curChar == 48)
                  {
                     if (kind > 99)
                        kind = 99;
                  }
                  else if (curChar == 49)
                  {
                     if (kind > 98)
                        kind = 98;
                  }
                  else if (curChar == 35)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAdd(1);
                  }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 42)
                     jjCheckNAddStates(5, 7);
                  break;
               case 5:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(6, 4);
                  break;
               case 6:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(6, 4);
                  break;
               case 7:
                  if (curChar == 35 && kind > 7)
                     kind = 7;
                  break;
               case 8:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 9:
                  if (curChar == 49 && kind > 98)
                     kind = 98;
                  break;
               case 10:
                  if (curChar == 48 && kind > 99)
                     kind = 99;
                  break;
               case 14:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 15:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 16:
                  if (curChar == 34 && kind > 103)
                     kind = 103;
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(0, 4);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if (curChar == 46)
                     jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(20);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(21);
                  break;
               case 23:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                     jjCheckNAdd(13);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                     jjCheckNAddTwoStates(12, 13);
                  }
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                     jjCheckNAddTwoStates(12, 13);
                  }
                  else if (curChar == 64)
                     jjCheckNAdd(12);
                  break;
               case 1:
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
               case 6:
                  jjCheckNAddTwoStates(6, 4);
                  break;
               case 11:
                  if (curChar == 64)
                     jjCheckNAdd(12);
                  break;
               case 12:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAddTwoStates(12, 13);
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAdd(13);
                  break;
               case 15:
                  jjAddStates(8, 9);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 5:
               case 6:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(6, 4);
                  break;
               case 15:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(8, 9);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 38 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   18, 19, 21, 22, 31, 4, 5, 7, 15, 16, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\61", "\60", null, null, null, 
null, null, null, null, null, null, null, null, null, "\53", "\55", "\52", "\57", 
"\136", "\75\75", "\75", "\41\75", "\74", "\76", "\74\75", "\76\75", "\174\174", 
"\46\46", "\41", "\50", "\51", null, null, "\73", null, "\54", null, null, null, null, 
null, null, null, null, "\173", "\175", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, "\72", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\56", "\53\53", "\55\55", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffff7b01L, 0x79fffffffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0xc0L, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[38];
private final int[] jjstateSet = new int[76];
protected char curChar;
/** Constructor. */
public UsqlParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public UsqlParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 38; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
